#If IsVimMode("_fnDown_") && IsVimMode("_normal_") && gRepeat > 0
d::SendFnKey("{Home}+{Down _n_}+{Home}^x", "_lineCopy_")
y::SendFnKey("{Home}+{Down _n_}+{Home}^c{Up}", "_lineCopy_")
g::SendFnKey("^{Home}{Down _n_}{Up}")

#If IsVimMode("_fnDown_") && IsVimMode("_normal_") 
[::SendFnKey("{Home}")
]::SendFnKey("{End}")
t::SendFnKey("{End}")
d::SendFnKey("{Home}+{End}^x{Del}", "", "_lineCopy_")
y::SendFnKey("{Home}+{End}^c{Home}", "", "_lineCopy_")
g::SendFnKey("^{Home}{Down _n_}{Up}")
c::SendFnKey("{BackSpace _n_}")
o::SendFnKey("{End}{Enter _n_}")
+o::SendFnKey("{Home}{Enter _n_}{Up _n_}")

#If IsVimMode("_fnDown_") && IsVimMode("_visual_") 
[::SendFnKey("+{Home}")
]::SendFnKey("+{End}")
t::SendFnKey("+{End}")

#If IsVimMode("_fnDown_")
m::SendFnKey("{Enter}")
BS::SendFnKey("{Del}")
+y::SendFnKey("^a^c{Right}")
+x::SendFnKey("^a^x")
!h::SendFnKey("!{Left}")
!l::SendFnKey("!{Right}")
1::SendFnKey("{F1}")
2::SendFnKey("{F2}")
3::SendFnKey("{F3}")
4::SendFnKey("{F4}")
5::SendFnKey("{F5}")
6::SendFnKey("{F6}")
7::SendFnKey("{F7}")
8::SendFnKey("{F8}")
9::SendFnKey("{F9}")
0::SendFnKey("{F10}")
-::SendFnKey("{F11}")
=::SendFnKey("{F12}")
Esc::SendFnKey("~")
^=::SoundSet +5  ; Increase master volume by 5%
^-::SoundSet -5  ; Decrease master volume by 5%
